spring:
  profiles:
    active: dev #使用dev环境配置
---
spring:
  config:
    activate:
      on-profile: product
---
spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    prefix: classpath:/static/
    cache: false

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8

  datasource:
    username: root
    password: 1122
    url: jdbc:mysql://localhost:3306/voter?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源

  #注意了，使用下面的邮箱配置，会导致应用启动很慢，注释掉可以加快启动速度方便测试，不过程序中需要做一定的处理，参考MailTool
#  mail:
#    #smtp服务主机  qq邮箱则为smtp.qq.com
#    host: smtp.qq.com
#    #服务协议
#    protocol: smtp
#    # 编码集
#    default-encoding: UTF-8
#    #发送邮件的账户
#    username: 2430640625@qq.com
#    #授权码
#    password: gkzdqymrmsvweafb
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:self/mapper/*.xml,classpath*:/mapper/**Mapper.xml
  type-aliases-package: personal.lyh.voter
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      id-type: AUTO #主键类型 自增
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
---

#-------------------------------------------------------------------------------------